name: nitsan/contact-us
typeName: nitsan_contactus
group: Website Starter Kit
prefixFields: true
prefixType: full

fields:

  - identifier: phone
    label: Phone number
    type: Number

  - identifier: email
    label: Email
    type: Email

  - identifier: address
    label: Address
    type: Textarea

  - identifier: latitude
    label: Latitude
    type: Text

  - identifier: longitude
    label: Longitude
    type: Text